language: node_js
node_js:
  - "9"
dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm i @angular/cli@8 -g
  - npm i

script:
  - ng build --prod
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 7eec8049c4b64f6b7821065fdc3b387eb0503dcb
  local_dir: dist/
  on:
    branch: master

